version: '2.0'

services:
  app:
    build:
      context: Dockerfiles/php
    image: adrianharabula/php7
    links:
      - mariadb:db
    volumes:
      - "./www/:/var/www/"
    ports:
      - "0.0.0.0:80:80"

  mariadb:
    image: mariadb:10.1
    environment:
    #  - MYSQL_ROOT_PASSWORD=toor
     - MYSQL_RANDOM_ROOT_PASSWORD=yes
     - MYSQL_DATABASE=mydb
     - MYSQL_USER=user
     - MYSQL_PASSWORD=pass
    volumes:
     - ./Dockerfiles/mariadb/scripts:/docker-entrypoint-initdb.d
    #  - ./Dockerfiles/mariadb/database:/var/lib/mysql
    ports:
     - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=pass
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
